#!/usr/local/bin/bash

names=('Roberto_Carlos_(cantante)' 'Camilo_Sesto' 'Glenn_Medeiros' 'Richard_Anthony' 'Gilbert_Bécaud' 'Lionel_Richie' 'Pablo_Abraira' 'Dani_Martín' 'Enrique_Guzmán_(cantante)' 'Lolita_(cantante)' 'Karina_(cantante_española)' 'Raúl_(cantante)' 'Chayanne' 'Alaska_y_Dinarama' 'Estopa_(banda)' 'Luis_Aguilé' 'Kaoma' 'Lou_Bega' 'Los_Bravos' 'Los_Payos' 'Miguel_Ángel_Muñoz' 'The_Communards' 'La_Oreja_de_Van_Gogh' 'Silver_Convention' 'Cher' 'Buraka_Som_Sistema' 'Boney_M.' 'Double_You' 'Whigfield' 'Becky_G' 'Natti_Natasha' 'Aitana_(cantante)' 'Sandro_Giacobbe' 'Pop-Tops' 'Pic-nic_(banda)' 'Umberto_Tozzi' 'Ricardo_Cocciante' 'Les_Surfs' 'Sandie_Shaw' 'Barry_Ryan' 'Enigma!' 'Patrick_Hernández' 'Londonbeat' 'F._R._David' 'Guru_Josh' 'Imagination_(banda)' 'Innocence_(Geraldine_Larrosa)' 'Anita_Ward' 'Ana_Belén' 'Víctor_Manuel_(cantante)' 'Culture_Club' 'Julio_Iglesias' 'Raphael_(cantante)' 'Roxette' 'Mecano_(banda)' 'Nino_Bravo' 'Mike_Oldfield' 'Tom_Jones_(cantante)' 'Dúo_Dinámico' 'Elton_John' 'Manolo_Otero' 'Carlos_Baute' 'Desireless' 'Los_Diablos' 'Eddy_Grant' 'Luis_Fonsi' 'Los_Planetas_(banda)' 'Violadores_del_Verso' 'Depeche_Mode' 'Europe' 'Astrud' )

nombres=('Roberto Carlos' 'Camilo Sesto' 'Glenn Medeiros' 'Richard Anthony' 'Gilbert Bécaud' 'Lionel Richie' 'Pablo Abraira' 'Dani Martín' 'Enrique Guzmán ' 'Lolita' 'Karina' 'Raúl' 'Chayanne' 'Alaska y Dinarama' 'Estopa' 'Luis Aguilé' 'Kaoma' 'Lou Bega' 'Los Bravos' 'Los Payos' 'Miguel Ángel Muñoz' 'The Communards' 'La Oreja de Van Gogh' 'Silver Convention' 'Cher' 'Buraka Som Sistema' 'Boney M.' 'Double You' 'Whigfield' 'Becky G' 'Natti Natasha' 'Aitana' 'Sandro Giacobbe' 'Pop-Tops' 'Pic-nic' 'Umberto Tozzi' 'Ricardo Cocciante' 'Les Surfs' 'Sandie Shaw' 'Barry Ryan' 'Enigma!' 'Patrick Hernández' 'Londonbeat' 'F. R. David' 'Guru Josh' 'Imagination' 'Innocence' 'Anita Ward' 'Ana Belén' 'Víctor Manuel' 'Culture Club' 'Julio Iglesias' 'Raphael' 'Roxette' 'Mecano' 'Nino Bravo' 'Mike Oldfield' 'Tom Jones' 'Dúo Dinámico' 'Elton John' 'Manolo Otero' 'Carlos Baute' 'Desireless' 'Los Diablos' 'Eddy Grant' 'Luis Fonsi' 'Los Planetas' 'Violadores del Verso' 'Depeche Mode' 'Europe' 'Astrud')


for (( i=0; i<${#names[@]}; ++i )); do
    sed -i "s/${names[$i]}/${nombres[$i]}/g" csv/"${nombres[$i]}".csv
done
